###
POST http://localhost:6868/api/v1/register
Content-Type: application/json

{
    "code": "2020606605",
    "password": "tunglv27@bssdev",
    "name": "Tùng DEV"
}

###
POST http://localhost:6868/api/v1/login
Content-Type: application/json

{
    "code": "2020606605",
    "password": "tunglv27@bssdev"
}